import { cloneElement, createContext, isValidElement, useContext, useMemo, useState } from 'react';

const AdminLanguageContext = createContext(null);
const LANGUAGE_KEY = 'systemAdminLanguage';

const translations = {
  'Welcome,': 'እንኳን ደህና መጡ፣',
  Admin: 'አስተዳዳሪ',
  'Admin account': 'የአስተዳዳሪ መለያ',
  'System Administrator': 'የስርዓት አስተዳዳሪ',
  'Dashboard': 'ዳሽቦርድ',
  'Users': 'ተጠቃሚዎች',
  'Roles & Permissions': 'ሚናዎች እና ፈቃዶች',
  'Departments': 'የሥራ ክፍሎች',
  'Positions': 'የሥራ መደቦች',
  'Reports': 'ሪፖርቶች',
  'Audit Logs': 'የክትትል መዝገቦች',
  'System Settings': 'የስርዓት ቅንብሮች',
  'EMPLOYEE CLEARANCE MANAGEMENT': 'የሰራተኞች ማጽዳት አስተዳደር',
  'Open System Administrator menu': 'የስርዓት አስተዳዳሪ ምናሌን ክፈት',
  'My Dashboard': 'ዳሽቦርዴ',
  'View Profile': 'መገለጫን ይመልከቱ',
  'Change Password': 'የይለፍ ቃል ይቀይሩ',
  'Dashboard Settings': 'የዳሽቦርድ ቅንብሮች',
  'Sign Out': 'ውጣ',
  'Notifications': 'ማሳወቂያዎች',
  'Open notifications': 'ማሳወቂያዎችን ክፈት',
  'Total Users': 'ጠቅላላ ተጠቃሚዎች',
  'All system users': 'ሁሉም የስርዓቱ ተጠቃሚዎች',
  'Active Users': 'ንቁ ተጠቃሚዎች',
  'Active accounts': 'ንቁ መለያዎች',
  'Inactive Users': 'ንቁ ያልሆኑ ተጠቃሚዎች',
  'Inactive accounts': 'ንቁ ያልሆኑ መለያዎች',
  'Total Employees': 'ጠቅላላ ሰራተኞች',
  'All employees': 'ሁሉም ሰራተኞች',
  'Total Clearance Requests': 'ጠቅላላ የማጽዳት ጥያቄዎች',
  'All requests': 'ሁሉም ጥያቄዎች',
  'Pending Requests': 'በመጠባበቅ ላይ ያሉ ጥያቄዎች',
  'Awaiting action': 'እርምጃ በመጠባበቅ ላይ',
  'Completed Clearances': 'የተጠናቀቁ ማጽዳቶች',
  'Successfully completed': 'በተሳካ ሁኔታ ተጠናቋል',
  'Rejected Requests': 'ውድቅ የተደረጉ ጥያቄዎች',
  'Rejected requests': 'ውድቅ የተደረጉ ጥያቄዎች',
  'System Admin Dashboard': 'የስርዓት አስተዳዳሪ ዳሽቦርድ',
  'User Management Overview': 'የተጠቃሚ አስተዳደር አጠቃላይ እይታ',
  'View All': 'ሁሉንም ይመልከቱ',
  'System Admins': 'የስርዓት አስተዳዳሪዎች',
  'HR Officers': 'የሰው ሀብት ኦፊሰሮች',
  'Department Officers': 'የክፍል ኦፊሰሮች',
  'Employees (Users)': 'ሰራተኞች (ተጠቃሚዎች)',
  'Active Accounts': 'ንቁ መለያዎች',
  'Inactive Accounts': 'ንቁ ያልሆኑ መለያዎች',
  'Clearance Requests Overview': 'የማጽዳት ጥያቄዎች አጠቃላይ እይታ',
  Total: 'ጠቅላላ',
  Pending: 'በመጠባበቅ ላይ',
  'In Progress': 'በሂደት ላይ',
  Completed: 'ተጠናቋል',
  Rejected: 'ውድቅ ተደርጓል',
  Overdue: 'ጊዜው ያለፈበት',
  'Organization Overview': 'የድርጅት አጠቃላይ እይታ',
  Campuses: 'ግቢዎች',
  'Colleges / Institutes': 'ኮሌጆች / ተቋማት',
  Sections: 'ክፍሎች',
  'Sections / Teams': 'ክፍሎች / ቡድኖች',
  'Job Grades': 'የሥራ ደረጃዎች',
  'Recent System Activity': 'የቅርብ ጊዜ የስርዓት እንቅስቃሴ',
  'No recent activity.': 'በቅርቡ ምንም እንቅስቃሴ የለም።',
  'Recently Added': 'በቅርቡ የተጨመሩ',
  'View Users': 'ተጠቃሚዎችን ይመልከቱ',
  'No users added yet.': 'እስካሁን ምንም ተጠቃሚ አልተጨመረም።',
  Employees: 'ሰራተኞች',
  'View Employees': 'ሰራተኞችን ይመልከቱ',
  'No employees added yet.': 'እስካሁን ምንም ሰራተኛ አልተጨመረም።',
  Employee: 'ሰራተኛ',
  'User Activity / Security': 'የተጠቃሚ እንቅስቃሴ / ደህንነት',
  'Last Login (System Admin)': 'የመጨረሻ መግቢያ (አስተዳዳሪ)',
  'Failed Login Attempts (Today)': 'ያልተሳኩ የመግቢያ ሙከራዎች (ዛሬ)',
  'Password Reset Requests (Today)': 'የይለፍ ቃል መቀየር ጥያቄዎች (ዛሬ)',
  'Recently Activated Accounts': 'በቅርቡ የነቁ መለያዎች',
  'Recently Deactivated Accounts': 'በቅርቡ የተዘጉ መለያዎች',
  'Quick Actions': 'ፈጣን እርምጃዎች',
  'Create User': 'ተጠቃሚ ፍጠር',
  'Manage Users': 'ተጠቃሚዎችን አስተዳድር',
  'Manage Employees': 'ሰራተኞችን አስተዳድር',
  'Manage Roles': 'ሚናዎችን አስተዳድር',
  'Manage Departments': 'የሥራ ክፍሎችን አስተዳድር',
  'Clearance Steps': 'የማጽዳት ደረጃዎች',
  'View Reports': 'ሪፖርቶችን ይመልከቱ',
  'Dashboard data could not be loaded from the database.': 'የዳሽቦርድ መረጃውን ከዳታቤዝ መጫን አልተቻለም።',
  'General Settings': 'አጠቃላይ ቅንብሮች',
  'Configure basic information about the university and system.': 'ስለ ዩኒቨርሲቲው እና ስርዓቱ መሠረታዊ መረጃዎችን ያዋቅሩ።',
  'University information': 'የዩኒቨርሲቲ መረጃ',
  'System name and logo': 'የስርዓት ስም እና አርማ',
  'Contact information': 'የመገኛ መረጃ',
  'Date, time and language settings': 'የቀን፣ ሰዓት እና ቋንቋ ቅንብሮች',
  'Manage Settings': 'ቅንብሮችን አስተዳድር',
  'Clearance Settings': 'የማጽዳት ቅንብሮች',
  'Configure employee clearance process and workflow.': 'የሰራተኛ ማጽዳት ሂደትን እና የሥራ ፍሰትን ያዋቅሩ።',
  'Required clearance offices': 'አስፈላጊ የማጽዳት ቢሮዎች',
  'Clearance workflow order': 'የማጽዳት የሥራ ፍሰት ቅደም ተከተል',
  'Request & approval settings': 'የጥያቄ እና ማጽደቅ ቅንብሮች',
  'Auto-complete options': 'በራስ-ሰር የማጠናቀቂያ አማራጮች',
  'Notification Settings': 'የማሳወቂያ ቅንብሮች',
  'Configure system notifications and email preferences.': 'የስርዓት ማሳወቂያዎችን እና የኢሜይል ምርጫዎችን ያዋቅሩ።',
  'Email notifications': 'የኢሜይል ማሳወቂያዎች',
  'In-app notifications': 'በመተግበሪያ ውስጥ ማሳወቂያዎች',
  'Notification templates': 'የማሳወቂያ አብነቶች',
  'Alert preferences': 'የማንቂያ ምርጫዎች',
  'Certificate Settings': 'የሰርተፊኬት ቅንብሮች',
  'Manage clearance certificate templates and options.': 'የማጽዳት ሰርተፊኬት አብነቶችን እና አማራጮችን ያስተዳድሩ።',
  'Certificate template': 'የሰርተፊኬት አብነት',
  'Logo and signature': 'አርማ እና ፊርማ',
  'Certificate number format': 'የሰርተፊኬት ቁጥር ቅርጸት',
  'QR code / verification options': 'የQR ኮድ / የማረጋገጫ አማራጮች',
  'Security Settings': 'የደህንነት ቅንብሮች',
  'Configure security policies and authentication rules.': 'የደህንነት ፖሊሲዎችን እና የማረጋገጫ ደንቦችን ያዋቅሩ።',
  'Password policy': 'የይለፍ ቃል ፖሊሲ',
  'Login attempt limits': 'የመግቢያ ሙከራ ገደቦች',
  'Session timeout': 'የክፍለ ጊዜ ጊዜ ማብቂያ',
  'First login password change': 'በመጀመሪያ መግቢያ የይለፍ ቃል መቀየር',
  'Backup & Maintenance': 'ምትኬ እና ጥገና',
  'Manage database backup and system maintenance.': 'የዳታቤዝ ምትኬን እና የስርዓት ጥገናን ያስተዳድሩ።',
  'Create database backup': 'የዳታቤዝ ምትኬ ፍጠር',
  'Backup history': 'የምትኬ ታሪክ',
  'Restore backup': 'ምትኬን መልስ',
  'Maintenance mode': 'የጥገና ሁነታ',
  'System settings apply across the entire system. Please update these settings carefully.': 'የስርዓት ቅንብሮች በመላው ስርዓቱ ላይ ተግባራዊ ይሆናሉ። እባክዎ እነዚህን ቅንብሮች በጥንቃቄ ያዘምኑ።',
  'Configure and manage the system settings and preferences': 'የስርዓት ቅንብሮችን እና ምርጫዎችን ያዋቅሩ እና ያስተዳድሩ',
  'Role Details': 'የሚና ዝርዝሮች',
  'Manage user roles and their permissions in the system.': 'በስርዓቱ ውስጥ የተጠቃሚ ሚናዎችን እና ፈቃዶቻቸውን ያስተዳድሩ።',
  'Add New Role': 'አዲስ ሚና ጨምር',
  'S No': 'ተ.ቁ',
  'Note': 'ማስታወሻ',
  Manage: 'አስተዳድር',
  'Open menu': 'ምናሌን ክፈት',
  'Contact Email': 'የመገኛ ኢሜይል',
  'Contact Phone': 'የመገኛ ስልክ',
  'System Description': 'የስርዓት መግለጫ',
  'Edit University and System Information': 'የዩኒቨርሲቲ እና የስርዓት መረጃን ያርትዑ',
  'Clearance Workflow': 'የማጽዳት የሥራ ፍሰት',
  'Configure Clearance Workflow': 'የማጽዳት የሥራ ፍሰትን ያዋቅሩ',
  'Required Clearance Offices': 'አስፈላጊ የማጽዳት ቢሮዎች',
  'Request Enable / Disable': 'ጥያቄን አንቃ / አሰናክል',
  'Email Notifications': 'የኢሜይል ማሳወቂያዎች',
  'In-App Notifications': 'በመተግበሪያ ውስጥ ማሳወቂያዎች',
  'New User Created': 'አዲስ ተጠቃሚ ተፈጥሯል',
  'New Employee Added': 'አዲስ ሰራተኛ ታክሏል',
  'Password Reset Requested': 'የይለፍ ቃል መቀየር ተጠይቋል',
  'Security Alert': 'የደህንነት ማንቂያ',
  'User Account Deactivated': 'የተጠቃሚ መለያ ተዘግቷል',
  'Employee Clearance Completed': 'የሰራተኛ ማጽዳት ተጠናቋል',
  'System Error Occurred': 'የስርዓት ስህተት ተከስቷል',
  'Backup Completed': 'ምትኬ ተጠናቋል',
  User: 'ተጠቃሚ',
  'Unnamed user': 'ስም ያልተሰጠው ተጠቃሚ',
  'No role': 'ሚና የለም',
  Home: 'መነሻ',
  'Employees & Users': 'ሰራተኞች እና ተጠቃሚዎች',
  'Administrator': 'አስተዳዳሪ',
  'HR Officer': 'የሰው ሀብት ኦፊሰር',
  'Department Approver': 'የሥራ ክፍል አጽዳቂ',
  'All Status': 'ሁሉም ሁኔታዎች',
  'Username': 'የተጠቃሚ ስም',
  'Page': 'ገጽ',
  'of': 'ከ',
  'Select all users': 'ሁሉንም ተጠቃሚዎች ይምረጡ',
  'New Password': 'አዲስ የይለፍ ቃል',
  'Enter new password': 'አዲስ የይለፍ ቃል ያስገቡ',
  'Confirm New Password': 'አዲሱን የይለፍ ቃል ያረጋግጡ',
  'Confirm new password': 'አዲሱን የይለፍ ቃል ያረጋግጡ',
  Cancel: 'ሰርዝ',
  Saving: 'በማስቀመጥ ላይ',
  'Update Password': 'የይለፍ ቃል አዘምን',
  'Role Type': 'የሚና ዓይነት',
  'All Departments': 'ሁሉም የሥራ ክፍሎች',
  'Department / Unit': 'የሥራ ክፍል / ክፍል',
  'Email Address': 'የኢሜይል አድራሻ',
  'Department/Unit': 'የሥራ ክፍል/ክፍል',
  'Retry': 'እንደገና ሞክር',
  'Loading users...': 'ተጠቃሚዎች በመጫን ላይ...',
  'No users found.': 'ምንም ተጠቃሚ አልተገኘም።',
  'Active': 'ንቁ',
  'Inactive': 'ንቁ ያልሆነ',
  'Deactivated': 'ተዘግቷል',
  'Pending Setup': 'ማዋቀር በመጠባበቅ ላይ',
  'Search': 'ፈልግ',
  'Search by name, ID, phone or email...': 'በስም፣ መለያ፣ ስልክ ወይም ኢሜይል ፈልግ...',
  'All Campuses': 'ሁሉም ግቢዎች',
  'All Types': 'ሁሉም ዓይነቶች',
  'Employment Type': 'የቅጥር ዓይነት',
  'No employees found.': 'ምንም ሰራተኛ አልተገኘም።',
  'Search roles...': 'ሚናዎችን ፈልግ...',
  'Delete the role': 'ሚናውን ይሰርዙ',
  'Role deleted successfully.': 'ሚናው በተሳካ ሁኔታ ተሰርዟል።',
  'Unable to delete role. Please try again.': 'ሚናውን መሰረዝ አልተቻለም። እባክዎ እንደገና ይሞክሩ።',
  'Export Excel': 'ወደ Excel ላክ',
  'Export PDF': 'ወደ PDF ላክ',
  'Search by User': 'በተጠቃሚ ፈልግ',
  'All Roles': 'ሁሉም ሚናዎች',
  'System Admin': 'የስርዓት አስተዳዳሪ',
  'Authentication': 'ማረጋገጫ',
  'Organization': 'ድርጅት',
  'Clearance Request': 'የማጽዳት ጥያቄ',
  'HR Clearance': 'የሰው ሀብት ማጽዳት',
  'Finance Clearance': 'የፋይናንስ ማጽዳት',
  'Property Clearance': 'የንብረት ማጽዳት',
  'IT Clearance': 'የአይቲ ማጽዳት',
  'Department Clearance': 'የሥራ ክፍል ማጽዳት',
  'Library Clearance': 'የቤተ መጻሕፍት ማጽዳት',
  'Final HR Clearance': 'የመጨረሻ የሰው ሀብት ማጽዳት',
  View: 'ይመልከቱ',
  Create: 'ፍጠር',
  Edit: 'አርትዕ',
  Delete: 'ሰርዝ',
  Approve: 'አጽድቅ',
  Reject: 'ውድቅ አድርግ',
  Export: 'ላክ',
  'System activities and audit trails': 'የስርዓት እንቅስቃሴዎች እና የክትትል መዝገቦች',
  'Search by user or action...': 'በተጠቃሚ ወይም እርምጃ ፈልግ...',
  Module: 'ሞጁል',
  'Date From': 'ከቀን',
  'Date To': 'እስከ ቀን',
  Apply: 'ተግብር',
  'Clear Filters': 'ማጣሪያዎችን አጽዳ',
  'No audit logs found.': 'ምንም የክትትል መዝገብ አልተገኘም።',
  'All notifications': 'ሁሉም ማሳወቂያዎች',
  'Mark all as read': 'ሁሉንም እንደተነበቡ ምልክት አድርግ',
  'No notifications found.': 'ምንም ማሳወቂያ አልተገኘም።',
  'University Name': 'የዩኒቨርሲቲ ስም',
  'System Name': 'የስርዓት ስም',
  Language: 'ቋንቋ',
  English: 'እንግሊዝኛ',
  Amharic: 'አማርኛ',
  Save: 'አስቀምጥ',
  'Save Changes': 'ለውጦችን አስቀምጥ',
  'Account security': 'የመለያ ደህንነት',
  Appearance: 'ገጽታ',
  'Dark mode': 'ጨለማ ሁነታ',
  'Use a darker appearance on this settings page.': 'በዚህ የቅንብር ገጽ ላይ ጨለማ ገጽታ ይጠቀሙ።',
  Status: 'ሁኔታ',
  All: 'ሁሉም',
  'Users List': 'የተጠቃሚዎች ዝርዝር',
  'Add New User': 'አዲስ ተጠቃሚ ጨምር',
  'System Users': 'የስርዓት ተጠቃሚዎች',
  'Full Name': 'ሙሉ ስም',
  Role: 'ሚና',
  'Linked Employee ID': 'የተገናኘ የሰራተኛ መለያ',
  Actions: 'እርምጃዎች',
  'View user': 'ተጠቃሚውን ይመልከቱ',
  'Edit user': 'ተጠቃሚውን ያርትዑ',
  'Reset Password': 'የይለፍ ቃል ይቀይሩ',
  Previous: 'ቀዳሚ',
  Next: 'ቀጣይ',
  Show: 'አሳይ',
  'Department Management': 'የሥራ ክፍል አስተዳደር',
  'Manage departments participating in the university clearance process.': 'በዩኒቨርሲቲው የማጽዳት ሂደት ውስጥ የሚሳተፉ የሥራ ክፍሎችን ያስተዳድሩ።',
  'Add New Department': 'አዲስ የሥራ ክፍል ጨምር',
  'Search departments': 'የሥራ ክፍሎችን ፈልግ',
  'Department Name': 'የሥራ ክፍል ስም',
  Code: 'ኮድ',
  Type: 'ዓይነት',
  Campus: 'ግቢ',
  'Department Head': 'የሥራ ክፍል ኃላፊ',
  Action: 'እርምጃ',
  'Loading departments...': 'የሥራ ክፍሎች በመጫን ላይ...',
  'No departments found.': 'ምንም የሥራ ክፍል አልተገኘም።',
  'View department': 'የሥራ ክፍሉን ይመልከቱ',
  'Edit department': 'የሥራ ክፍሉን ያርትዑ',
  'Employee List': 'የሰራተኞች ዝርዝር',
  'View and manage all employees in the organization.': 'በድርጅቱ ውስጥ ያሉ ሰራተኞችን ይመልከቱ እና ያስተዳድሩ።',
  'Add Employee': 'ሰራተኛ ጨምር',
  Department: 'የሥራ ክፍል',
  Reset: 'አጽዳ',
  'Position / Job Title': 'የሥራ መደብ / የሥራ ርዕስ',
  'All Positions': 'ሁሉም የሥራ መደቦች',
  'All Positions / Job Titles': 'ሁሉም የሥራ መደቦች / የሥራ ርዕሶች',
  'Manage all job positions in the university': 'በዩኒቨርሲቲው ያሉ ሁሉንም የሥራ መደቦች ያስተዳድሩ',
  'Search position by name...': 'የሥራ መደቡን በስም ፈልግ...',
  'Filter by Department': 'በሥራ ክፍል አጣራ',
  'Filter by Status': 'በሁኔታ አጣራ',
  'Add New Position': 'አዲስ የሥራ መደብ ጨምር',
  'Total Positions:': 'ጠቅላላ የሥራ መደቦች፦',
  'Department / Office': 'የሥራ ክፍል / ቢሮ',
  Description: 'መግለጫ',
  'Created At': 'የተፈጠረበት ቀን',
  'Loading positions...': 'የሥራ መደቦች በመጫን ላይ...',
  'No positions match the current filters.': 'ከአሁኑ ማጣሪያዎች ጋር የሚዛመድ የሥራ መደብ የለም።',
  'Role & Permissions': 'ሚና እና ፈቃዶች',
  Roles: 'ሚናዎች',
  Permissions: 'ፈቃዶች',
  'System activities and user actions log': 'የስርዓት እንቅስቃሴዎች እና የተጠቃሚ እርምጃዎች መዝገብ',
  'Unable to load notifications.': 'ማሳወቂያዎችን መጫን አልተቻለም።',
  'BAHIR DAR UNIVERSITY': 'ባህር ዳር ዩኒቨርሲቲ',
  'S NO': 'ተ.ቁ',
  'Departments per page': 'የሥራ ክፍሎች በአንድ ገጽ',
  'Employees per page': 'ሰራተኞች በአንድ ገጽ',
  'Users per page': 'ተጠቃሚዎች በአንድ ገጽ',
  'Employee ID': 'የሰራተኛ መለያ',
  Photo: 'ፎቶ',
  Gender: 'ጾታ',
  Position: 'የሥራ መደብ',
  Phone: 'ስልክ',
  'Loading employees...': 'ሰራተኞች በመጫን ላይ...',
  'Resetting password for:': 'የሚከተለውን የተጠቃሚ የይለፍ ቃል በመቀየር ላይ፦',
  'Department Officer': 'የሥራ ክፍል ኦፊሰር',
  'Manage your dashboard appearance and account settings.': 'የዳሽቦርድዎን ገጽታ እና የመለያ ቅንብሮች ያስተዳድሩ።',
  'Cannot connect to the API server. Make sure it is running, then try again.': 'ከኤፒአይ አገልጋዩ ጋር መገናኘት አልተቻለም። አገልጋዩ መስራቱን ያረጋግጡና እንደገና ይሞክሩ።',
  'The API did not respond within 10 seconds. Check the server and database, then retry.': 'ኤፒአይው በ10 ሰከንድ ውስጥ ምላሽ አልሰጠም። አገልጋዩን እና ዳታቤዙን ያረጋግጡና እንደገና ይሞክሩ።',
  'Unable to load users.': 'ተጠቃሚዎችን መጫን አልተቻለም።',
  'Saving...': 'በማስቀመጥ ላይ...',
  'All users': 'ሁሉም ተጠቃሚዎች',
  'View position': 'የሥራ መደቡን ይመልከቱ',
  'Edit position': 'የሥራ መደቡን ያርትዑ',
  'Delete position': 'የሥራ መደቡን ሰርዝ',
  'System Admin Dashboard - Reports': 'የስርዓት አስተዳዳሪ ዳሽቦርድ - ሪፖርቶች',
  'View and analyze clearance reports and statistics': 'የማጽዳት ሪፖርቶችን እና ስታቲስቲክስን ይመልከቱ እና ይተንትኑ',
  'From date': 'ከቀን',
  'To date': 'እስከ ቀን',
  'Generate Report': 'ሪፖርት ፍጠር',
  'Clearance Status Distribution': 'የማጽዳት ሁኔታ ስርጭት',
  'Total Requests': 'ጠቅላላ ጥያቄዎች',
  'Monthly Clearance Trend (This Year)': 'ወርሃዊ የማጽዳት አዝማሚያ (በዚህ ዓመት)',
  'Requests by Campus': 'ጥያቄዎች በግቢ',
  'View All Employees': 'ሁሉንም ሰራተኞች ይመልከቱ',
  'All Modules': 'ሁሉም ሞጁሎች',
  'All Actions': 'ሁሉም እርምጃዎች',
  'From Date': 'ከቀን',
  'To Date': 'እስከ ቀን',
  'Apply Filter': 'ማጣሪያ ተግብር',
  'Log ID': 'የመዝገብ መለያ',
  'IP Address': 'የአይፒ አድራሻ',
  'Date & Time': 'ቀን እና ሰዓት',
  'Loading audit logs...': 'የክትትል መዝገቦች በመጫን ላይ...',
  Failed: 'አልተሳካም',
  Success: 'ተሳክቷል',
  'Super Administrator': 'ከፍተኛ አስተዳዳሪ',
  'Unable to load audit logs.': 'የክትትል መዝገቦችን መጫን አልተቻለም።',
  'Unable to update notification status.': 'የማሳወቂያውን ሁኔታ ማዘመን አልተቻለም።',
  'Unable to delete notification: notification id is missing.': 'ማሳወቂያውን መሰረዝ አልተቻለም፦ የማሳወቂያ መለያ ጠፍቷል።',
  'Unable to delete notification.': 'ማሳወቂያውን መሰረዝ አልተቻለም።',
  unread: 'ያልተነበቡ',
  Unread: 'ያልተነበቡ',
  Request: 'ጥያቄ',
  'Delete notification': 'ማሳወቂያን ሰርዝ',
  'Unread Summary': 'ያልተነበቡ ማጠቃለያ',
  to: 'እስከ',
  modules: 'ሞጁሎች',
  'Module / Feature': 'ሞጁል / ባህሪ',
  'Manage employee information and clearance requests.': 'የሰራተኛ መረጃን እና የማጽዳት ጥያቄዎችን ያስተዳድሩ።',
  'Users with this role': 'ይህ ሚና ያላቸው ተጠቃሚዎች',
  'Edit Role': 'ሚናን አርትዕ',
  'Deleting...': 'በመሰረዝ ላይ...',
  'Delete Role': 'ሚናን ሰርዝ',
  'More role actions': 'ተጨማሪ የሚና እርምጃዎች',
  Showing: 'በማሳየት ላይ',
  Allowed: 'ተፈቅዷል',
  Denied: 'ተከልክሏል',
  'Select a role to manage its permissions.': 'ፈቃዶቹን ለማስተዳደር ሚና ይምረጡ።',
  Account: 'መለያ',
  'Current Password': 'የአሁኑ የይለፍ ቃል',
  'Update your account password.': 'የመለያዎን የይለፍ ቃል ያዘምኑ።',
  'New passwords do not match.': 'አዲሶቹ የይለፍ ቃሎች አይዛመዱም።',
  'Password changed successfully.': 'የይለፍ ቃሉ በተሳካ ሁኔታ ተቀይሯል።',
  'Unable to change password.': 'የይለፍ ቃሉን መቀየር አልተቻለም።',
  'Changing Password...': 'የይለፍ ቃሉን በመቀየር ላይ...',
  'Unable to identify the signed-in administrator.': 'የገባውን አስተዳዳሪ መለየት አልተቻለም።',
  'Unable to load profile.': 'መገለጫውን መጫን አልተቻለም።',
  'Your authenticated account details.': 'የተረጋገጠው የመለያዎ ዝርዝሮች።',
  'Profile changes saved.': 'የመገለጫ ለውጦች ተቀምጠዋል።',
  'Unable to update profile.': 'መገለጫውን ማዘመን አልተቻለም።',
  'Choose a JPG, PNG, or GIF image.': 'JPG፣ PNG ወይም GIF ምስል ይምረጡ።',
  'The profile image must be smaller than 2 MB.': 'የመገለጫ ምስሉ ከ2 MB በታች መሆን አለበት።',
  'Profile photo updated.': 'የመገለጫ ፎቶ ተዘምኗል።',
  'Unable to update profile photo.': 'የመገለጫ ፎቶን ማዘመን አልተቻለም።',
  'Unable to read the selected image.': 'የተመረጠውን ምስል ማንበብ አልተቻለም።',
  'Loading profile...': 'መገለጫው በመጫን ላይ...',
  'Role / Title': 'ሚና / ማዕረግ',
  'Not assigned': 'አልተመደበም',
  'Enter phone number': 'ስልክ ቁጥር ያስገቡ',
  'Uploading...': 'በመጫን ላይ...',
  'Change Profile Photo': 'የመገለጫ ፎቶን ቀይር',
  'Saving Profile...': 'መገለጫን በማስቀመጥ ላይ...',
  'Save Profile Changes': 'የመገለጫ ለውጦችን አስቀምጥ',
  'Add Role': 'ሚና ጨምር',
  'Create new role information': 'አዲስ የሚና መረጃ ፍጠር',
  'Set Permissions': 'ፈቃዶችን አዘጋጅ',
  'Assign permissions to this role': 'ለዚህ ሚና ፈቃዶችን መድብ',
  'Review & Save': 'ገምግም እና አስቀምጥ',
  'Review and save the role': 'ሚናውን ገምግም እና አስቀምጥ',
  'Add Role Information': 'የሚና መረጃ ጨምር',
  'Role Name': 'የሚና ስም',
  'Enter role name': 'የሚና ስም ያስገቡ',
  'Enter a unique name for the role.': 'ለሚናው ልዩ ስም ያስገቡ።',
  'Enter role description (optional)': 'የሚና መግለጫ ያስገቡ (አማራጭ)',
  'Briefly describe what this role is responsible for.': 'ይህ ሚና ምን እንደሚያስተዳድር በአጭሩ ይግለጹ።',
  'Select role status.': 'የሚናውን ሁኔታ ይምረጡ።',
  'Select the permissions that this role will have.': 'ይህ ሚና የሚኖረውን ፈቃዶች ይምረጡ።',
  'Select All': 'ሁሉንም ይምረጡ',
  'Deselect All': 'ሁሉንም ምርጫ ያንሱ',
  'Next: Set Permissions': 'ቀጣይ፦ ፈቃዶችን ያዘጋጁ',
  'Next: Review & Save': 'ቀጣይ፦ ይገምግሙ እና ያስቀምጡ',
  'Save Role': 'ሚናን አስቀምጥ',
  'Saving role...': 'ሚናን በማስቀመጥ ላይ...',
  'Role name is required.': 'የሚና ስም ያስፈልጋል።',
  'Unable to reach the server. Please make sure the backend is running.': 'ከአገልጋዩ ጋር መገናኘት አልተቻለም። የጀርባ አገልጋዩ መስራቱን ያረጋግጡ።',
  'Unable to save role. Please try again.': 'ሚናውን ማስቀመጥ አልተቻለም። እንደገና ይሞክሩ።',
  'Account Information': 'የመለያ መረጃ',
  'Select Employee': 'ሰራተኛ ይምረጡ',
  'Search Employee': 'ሰራተኛ ፈልግ',
  'Search by ID, name or phone...': 'በመለያ፣ ስም ወይም ስልክ ፈልግ...',
  'Select employee': 'ሰራተኛ ይምረጡ',
  'No employees found': 'ምንም ሰራተኛ አልተገኘም',
  'Enter username': 'የተጠቃሚ ስም ያስገቡ',
  'Temporary Password': 'ጊዜያዊ የይለፍ ቃል',
  'Confirm Password': 'የይለፍ ቃል ያረጋግጡ',
  'First Login Password Change': 'በመጀመሪያ መግቢያ የይለፍ ቃል መቀየር',
  Required: 'አስፈላጊ',
  'Not required': 'አስፈላጊ አይደለም',
  'Role & Access': 'ሚና እና መዳረሻ',
  'Account Status': 'የመለያ ሁኔታ',
  'Enable login access for this user': 'ለዚህ ተጠቃሚ የመግቢያ ፈቃድ አንቃ',
  Creating: 'በመፍጠር ላይ',
  'Creating...': 'በመፍጠር ላይ...',
  'Loading settings...': 'ቅንብሮች በመጫን ላይ...',
  'Configure Clearance Certificate': 'የማጽዳት ሰርተፊኬትን ያዋቅሩ',
  'Configure Security Rules': 'የደህንነት ደንቦችን ያዋቅሩ',
  'Backup and Maintenance Settings': 'የምትኬ እና የጥገና ቅንብሮች',
  Back: 'ተመለስ',
  'No description provided.': 'ምንም መግለጫ አልተሰጠም።',
  'Not provided': 'አልተሰጠም',
  'Selected permissions': 'የተመረጡ ፈቃዶች',
  selected: 'ተመርጠዋል',
  'Loading role...': 'ሚናው በመጫን ላይ...',
  'Role Information': 'የሚና መረጃ',
  'Role Description': 'የሚና መግለጫ',
  'Role Status': 'የሚና ሁኔታ',
  'User Information': 'የተጠቃሚ መረጃ',
  'Loading user information...': 'የተጠቃሚ መረጃ በመጫን ላይ...',
  'User not found.': 'ተጠቃሚው አልተገኘም።',
  'Back to users': 'ወደ ተጠቃሚዎች ተመለስ',
  'Edit User': 'ተጠቃሚን አርትዕ',
  'User ID is missing. Please return to the users list and select a user.': 'የተጠቃሚ መለያ ጠፍቷል። ወደ ተጠቃሚዎች ዝርዝር ተመልሰው ተጠቃሚ ይምረጡ።',
  'Unable to load user information.': 'የተጠቃሚ መረጃን መጫን አልተቻለም።',
  'User Management': 'የተጠቃሚ አስተዳደር',
  '1. Select Employee': '1. ሰራተኛ ይምረጡ',
  '2. Account Information': '2. የመለያ መረጃ',
  '3. Role & Access': '3. ሚና እና መዳረሻ',
  'Employee *': 'ሰራተኛ *',
  'Loading roles...': 'ሚናዎች በመጫን ላይ...',
  'Select role': 'ሚና ይምረጡ',
  'Role *': 'ሚና *',
  'Account Status *': 'የመለያ ሁኔታ *',
};

function originalOptionText(node) {
  if (typeof node === 'string') return node;
  if (Array.isArray(node)) return node.map(originalOptionText).join('');
  return isValidElement(node) ? originalOptionText(node.props.children) : '';
}

function translateAdminNode(node, t) {
  if (typeof node === 'string') return t(node);
  if (Array.isArray(node)) return node.map((child) => translateAdminNode(child, t));
  if (!isValidElement(node)) return node;

  const props = { ...node.props };
  for (const name of ['aria-label', 'label', 'placeholder', 'title']) {
    if (typeof props[name] === 'string') props[name] = t(props[name]);
  }
  const children = translateAdminNode(node.props.children, t);
  if (node.type === 'option' && props.value === undefined) {
    props.value = originalOptionText(node.props.children).trim();
  }
  return cloneElement(node, props, children);
}

export function AdminTranslatedView({ children }) {
  const { t } = useOptionalAdminLanguage();
  return translateAdminNode(children, t);
}

export function AdminLanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => (
    localStorage.getItem(LANGUAGE_KEY) === 'am' ? 'am' : 'en'
  ));

  const setLanguage = (nextLanguage) => {
    const next = nextLanguage === 'am' ? 'am' : 'en';
    localStorage.setItem(LANGUAGE_KEY, next);
    setLanguageState(next);
  };

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (english, amharic) => language === 'am' ? (amharic || translations[english] || english) : english,
  }), [language]);

  return <AdminLanguageContext.Provider value={value}>{children}</AdminLanguageContext.Provider>;
}

export function useAdminLanguage() {
  const context = useContext(AdminLanguageContext);
  if (!context) throw new Error('useAdminLanguage must be used inside AdminLanguageProvider.');
  return context;
}

export function useOptionalAdminLanguage() {
  const context = useContext(AdminLanguageContext);
  return context || { language: 'en', t: (english) => english };
}
