import React, { useCallback, useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';
import {
  Download,
  FileSpreadsheet,
  Filter,
  Printer,
  RefreshCw,
  WalletCards,
} from 'lucide-react';

const API_BASE_URL = (import.meta.env.VITE_API_URL || 'http://localhost:3000')
  .replace(/\/api\/clearance\/?$/, '')
  .replace(/\/api\/?$/, '');
const REPORT_URL = `${API_BASE_URL}/api/finance/reports`;
const CHART_COLORS = ['#16a34a', '#f59e0b', '#2563eb', '#dc2626', '#64748b'];

const getAuthConfig = () => {
  const token = localStorage.getItem('token');
  return { headers: token ? { Authorization: `Bearer ${token}` } : {} };
};

const localDateValue = (date) => {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

const getCurrentMonthRange = () => {
  const today = new Date();
  return {
    startDate: localDateValue(new Date(today.getFullYear(), today.getMonth(), 1)),
    endDate: localDateValue(today),
  };
};

const INITIAL_FILTERS = {
  period: 'monthly',
  ...getCurrentMonthRange(),
  department: '',
  campus: '',
  clearanceReason: '',
  debtType: '',
  status: '',
};

const money = (value) => `ETB ${Number(value || 0).toLocaleString('en-US', {
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
})}`;

const dateTime = (value) => value
  ? new Date(value).toLocaleString()
  : '—';

const STATUS_LABELS = [
  ['cleared', 'Cleared'],
  ['outstanding', 'Outstanding'],
  ['pending', 'Pending'],
  ['underReview', 'Under Review'],
  ['returned', 'Returned'],
  ['rejected', 'Rejected'],
];

export default function FinanceReportsPage() {
  const [filters, setFilters] = useState(INITIAL_FILTERS);
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const loadReport = useCallback(async (reportFilters, shouldAudit = false) => {
    setLoading(true);
    setError('');
    try {
      const response = shouldAudit
        ? await axios.post(`${REPORT_URL}/generate`, reportFilters, {
          ...getAuthConfig(),
          headers: { ...getAuthConfig().headers, 'Content-Type': 'application/json' },
        })
        : await axios.get(`${REPORT_URL}/dashboard`, {
          ...getAuthConfig(),
          params: reportFilters,
        });
      if (!response.data?.success || !response.data.data) {
        throw new Error(response.data?.message || 'Unable to load finance reports.');
      }
      setReport(response.data.data);
    } catch (requestError) {
      setError(requestError.response?.data?.message || requestError.message || 'Unable to load finance reports.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadReport(INITIAL_FILTERS);
  }, [loadReport]);

  const statusData = useMemo(() => STATUS_LABELS
    .map(([key, name]) => ({ name, value: Number(report?.clearanceStatus?.[key] || 0) }))
    .filter((item) => item.value > 0), [report]);

  const handleFilterChange = (event) => {
    const { name, value } = event.target;
    setFilters((current) => ({ ...current, [name]: value }));
  };

  const submitFilters = (event) => {
    event.preventDefault();
    if (filters.period === 'custom' && (!filters.startDate || !filters.endDate)) {
      setError('Choose both start and end dates for the custom range.');
      return;
    }
    if (filters.period === 'custom' && filters.startDate > filters.endDate) {
      setError('The start date must be on or before the end date.');
      return;
    }
    loadReport(filters, true);
  };

  const resetFilters = () => {
    setFilters(INITIAL_FILTERS);
    loadReport(INITIAL_FILTERS);
  };

  const exportExcel = () => {
    const rows = report?.rows || [];
    const worksheet = XLSX.utils.json_to_sheet(rows.map((row) => ({
      'Request ID': row.requestId,
      Employee: row.employeeName,
      'Employee ID': row.employeeId,
      Department: row.department,
      'Clearance Reason': row.clearanceReason,
      'Debt Type': row.debtType,
      'Debt (ETB)': row.debt,
      'Paid (ETB)': row.paid,
      'Balance (ETB)': row.balance,
      Status: row.status,
    })));
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Financial Report');
    XLSX.writeFile(workbook, 'finance-financial-report.xlsx');
  };

  const exportPdf = () => {
    const pdf = new jsPDF({ orientation: 'landscape' });
    pdf.setFontSize(16);
    pdf.text('BDU Employee Clearance - Financial Report', 14, 16);
    pdf.setFontSize(9);
    pdf.text(`Generated by ${report?.generatedBy || 'Finance Officer'} | ${dateTime(report?.generatedAt)}`, 14, 23);
    autoTable(pdf, {
      startY: 29,
      head: [['Request ID', 'Employee', 'Department', 'Clearance Reason', 'Debt', 'Paid', 'Balance', 'Status']],
      body: (report?.rows || []).map((row) => [
        row.requestId,
        `${row.employeeName} (${row.employeeId})`,
        row.department,
        row.clearanceReason,
        money(row.debt),
        money(row.paid),
        money(row.balance),
        row.status,
      ]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: [30, 64, 175] },
    });
    pdf.save('finance-financial-report.pdf');
  };

  const summary = report?.summary || {};
  const cards = [
    { label: 'Total Requests', value: Number(summary.totalRequests || 0).toLocaleString(), tone: 'bg-blue-50 text-blue-700' },
    { label: 'Cleared', value: Number(summary.cleared || 0).toLocaleString(), tone: 'bg-emerald-50 text-emerald-700' },
    { label: 'Outstanding', value: Number(summary.outstanding || 0).toLocaleString(), tone: 'bg-amber-50 text-amber-700' },
    { label: 'Amount Owed', value: money(summary.amountOwed), tone: 'bg-rose-50 text-rose-700' },
  ];

  return (
    <main className="min-h-screen space-y-3 bg-slate-50 p-3 sm:p-4 md:p-5 print:bg-white print:p-0">
      <header className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center print:hidden">
        <div className="flex items-center gap-3">
          <span className="rounded-xl bg-blue-100 p-2.5 text-blue-700"><WalletCards size={22} /></span>
          <div>
            <h1 className="text-xl font-bold text-slate-900">Finance Reports</h1>
            <p className="text-xs text-slate-500">Financial clearance and debt recovery overview</p>
          </div>
        </div>
        {report && (
          <p className="text-[10px] text-slate-500">
            Generated by <span className="font-semibold">{report.generatedBy}</span>
            {' · '}{dateTime(report.generatedAt)}
          </p>
        )}
      </header>

      {error && (
        <div role="alert" className="flex items-center justify-between gap-3 rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-xs text-rose-700">
          <span>{error}</span>
          <button type="button" onClick={() => loadReport(filters)} disabled={loading} className="font-semibold underline">Retry</button>
        </div>
      )}

      <section aria-label="Financial report summary" className="grid grid-cols-2 gap-2 lg:grid-cols-4">
        {cards.map((card) => (
          <article key={card.label} className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm">
            <p className="text-[11px] font-medium text-slate-500">{card.label}</p>
            <p className={`mt-1 text-lg font-bold ${card.tone.split(' ')[1]}`}>{card.value}</p>
          </article>
        ))}
      </section>

      <section className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm print:hidden">
        <form onSubmit={submitFilters}>
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-7">
            <SelectField label="Period" name="period" value={filters.period} onChange={handleFilterChange}>
              <option value="today">Today</option>
              <option value="weekly">This Week</option>
              <option value="monthly">This Month</option>
              <option value="yearly">This Year</option>
              <option value="custom">Custom Range</option>
            </SelectField>
            <SelectField label="Department" name="department" value={filters.department} onChange={handleFilterChange}>
              <option value="">All Departments</option>
              {(report?.options?.departments || []).map((item) => <option key={item} value={item}>{item}</option>)}
            </SelectField>
            <SelectField label="Campus" name="campus" value={filters.campus} onChange={handleFilterChange}>
              <option value="">All Campuses</option>
              {(report?.options?.campuses || []).map((item) => <option key={item} value={item}>{item}</option>)}
            </SelectField>
            <SelectField label="Clearance Reason" name="clearanceReason" value={filters.clearanceReason} onChange={handleFilterChange}>
              <option value="">All Reasons</option>
              {(report?.options?.clearanceReasons || []).map((item) => <option key={item} value={item}>{item}</option>)}
            </SelectField>
            <SelectField label="Debt Type" name="debtType" value={filters.debtType} onChange={handleFilterChange}>
              <option value="">All Debt Types</option>
              {(report?.options?.debtTypes || []).map((item) => <option key={item} value={item}>{item}</option>)}
            </SelectField>
            <SelectField label="Financial Status" name="status" value={filters.status} onChange={handleFilterChange}>
              <option value="">All Statuses</option>
              {['Cleared', 'Outstanding', 'Pending', 'Under Review', 'Returned', 'Rejected'].map((item) => (
                <option key={item} value={item}>{item}</option>
              ))}
            </SelectField>
            <div className="flex items-end gap-1.5">
              <button type="submit" disabled={loading} className="inline-flex flex-1 items-center justify-center gap-1 rounded-lg bg-blue-600 px-2 py-2 text-[10px] font-semibold text-white hover:bg-blue-700 disabled:opacity-60">
                {loading ? <RefreshCw size={13} className="animate-spin" /> : <Filter size={13} />}
                Generate
              </button>
              <button type="button" onClick={resetFilters} disabled={loading} className="rounded-lg border border-slate-200 px-2 py-2 text-[10px] font-semibold text-slate-600 hover:bg-slate-50">
                Reset
              </button>
            </div>
          </div>
          {filters.period === 'custom' && (
            <div className="mt-2 grid max-w-md grid-cols-2 gap-2">
              <DateField label="From Date" name="startDate" value={filters.startDate} onChange={handleFilterChange} />
              <DateField label="To Date" name="endDate" value={filters.endDate} onChange={handleFilterChange} />
            </div>
          )}
        </form>
      </section>

      <section className="grid gap-3 lg:grid-cols-2">
        <article className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm">
          <h2 className="text-xs font-bold text-slate-800">Financial Clearance Status</h2>
          <div className="mt-1 flex h-44 items-center">
            <div className="h-44 min-w-0 flex-1">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie data={statusData} dataKey="value" nameKey="name" innerRadius={42} outerRadius={68} paddingAngle={2}>
                    {statusData.map((entry, index) => <Cell key={entry.name} fill={CHART_COLORS[index % CHART_COLORS.length]} />)}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
            </div>
            <div className="flex min-w-28 flex-col gap-1.5 text-[10px] text-slate-600">
              {STATUS_LABELS.map(([key, label], index) => (
                <span key={key} className="flex items-center gap-1.5">
                  <i className="h-2 w-2 rounded-full" style={{ backgroundColor: CHART_COLORS[index % CHART_COLORS.length] }} />
                  {label} <strong className="ml-auto text-slate-800">{report?.clearanceStatus?.[key] || 0}</strong>
                </span>
              ))}
            </div>
          </div>
        </article>

        <article className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm">
          <h2 className="text-xs font-bold text-slate-800">Monthly Debt Recovery</h2>
          <div className="mt-1 h-44">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={report?.monthlyRecovery || []} margin={{ top: 8, right: 10, left: 4, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey="month" tick={{ fontSize: 10 }} />
                <YAxis tick={{ fontSize: 9 }} tickFormatter={(value) => Number(value).toLocaleString()} />
                <Tooltip formatter={(value) => money(value)} />
                <Bar dataKey="recovered" name="Debt Recovered" fill="#2563eb" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </article>
      </section>

      <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        <header className="flex flex-col gap-3 border-b border-slate-200 p-3 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 className="text-sm font-bold text-slate-900">Detailed Financial Report</h2>
            <p className="text-[10px] text-slate-500">
              {report?.rows?.length || 0} record{report?.rows?.length === 1 ? '' : 's'}
              {report?.period?.startDate && ` · ${report.period.startDate} — ${report.period.endDate}`}
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-1.5 print:hidden">
            <button type="button" onClick={exportExcel} disabled={!report || loading} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-2.5 py-2 text-[10px] font-semibold text-white hover:bg-emerald-700 disabled:opacity-50">
              <FileSpreadsheet size={13} /> Export Excel
            </button>
            <button type="button" onClick={exportPdf} disabled={!report || loading} className="inline-flex items-center gap-1 rounded-lg bg-rose-600 px-2.5 py-2 text-[10px] font-semibold text-white hover:bg-rose-700 disabled:opacity-50">
              <Download size={13} /> Export PDF
            </button>
            <button type="button" onClick={() => window.print()} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-2 text-[10px] font-semibold text-slate-700 hover:bg-slate-50">
              <Printer size={13} /> Print
            </button>
          </div>
        </header>
        <div className="overflow-x-auto">
          <table className="w-full min-w-[950px] text-left text-[11px]">
            <thead className="bg-slate-50 text-[9px] uppercase tracking-wide text-slate-500">
              <tr>
                {['Request ID', 'Employee', 'Department', 'Clearance Reason', 'Debt', 'Paid', 'Balance', 'Status'].map((label) => (
                  <th key={label} className="px-3 py-2.5 font-semibold">{label}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {loading ? (
                <tr><td colSpan="8" className="p-8 text-center text-slate-400">Loading financial report…</td></tr>
              ) : report?.rows?.length ? report.rows.map((row) => (
                <tr key={row._id} className="hover:bg-slate-50">
                  <td className="px-3 py-2.5 font-semibold text-slate-700">{row.requestId || '—'}</td>
                  <td className="px-3 py-2.5">
                    <p className="font-semibold text-slate-900">{row.employeeName}</p>
                    <p className="text-[9px] text-slate-400">{row.employeeId}</p>
                  </td>
                  <td className="px-3 py-2.5">{row.department || '—'}</td>
                  <td className="px-3 py-2.5">{row.clearanceReason || '—'}{row.debtType ? ` · ${row.debtType}` : ''}</td>
                  <td className="px-3 py-2.5 font-medium">{money(row.debt)}</td>
                  <td className="px-3 py-2.5 font-medium text-emerald-700">{money(row.paid)}</td>
                  <td className={`px-3 py-2.5 font-bold ${row.balance > 0 ? 'text-rose-600' : 'text-emerald-700'}`}>{money(row.balance)}</td>
                  <td className="px-3 py-2.5">
                    <span className={`rounded-full px-2 py-1 text-[9px] font-semibold ${row.status === 'Cleared' ? 'bg-emerald-50 text-emerald-700' : row.status === 'Outstanding' ? 'bg-amber-50 text-amber-700' : 'bg-blue-50 text-blue-700'}`}>
                      {row.status}
                    </span>
                  </td>
                </tr>
              )) : (
                <tr><td colSpan="8" className="p-8 text-center text-slate-400">No financial records match the selected filters.</td></tr>
              )}
            </tbody>
            {!!report?.rows?.length && (
              <tfoot className="border-t border-slate-200 bg-slate-50 font-bold text-slate-700">
                <tr>
                  <td colSpan="4" className="px-3 py-2.5 text-right">Totals</td>
                  <td className="px-3 py-2.5">{money(report.rows.reduce((sum, row) => sum + row.debt, 0))}</td>
                  <td className="px-3 py-2.5 text-emerald-700">{money(report.rows.reduce((sum, row) => sum + row.paid, 0))}</td>
                  <td className="px-3 py-2.5 text-rose-700">{money(report.rows.reduce((sum, row) => sum + row.balance, 0))}</td>
                  <td />
                </tr>
              </tfoot>
            )}
          </table>
        </div>
      </section>

      {report && (
        <footer className="text-right text-[10px] text-slate-400 print:block">
          Report generated by {report.generatedBy} at {dateTime(report.generatedAt)}
        </footer>
      )}
    </main>
  );
}

function SelectField({ label, name, value, onChange, children }) {
  return (
    <label className="min-w-0 text-[10px] font-semibold text-slate-600">
      {label}
      <select name={name} value={value} onChange={onChange} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-2 py-2 text-[11px] outline-none focus:border-blue-500">
        {children}
      </select>
    </label>
  );
}

function DateField({ label, name, value, onChange }) {
  return (
    <label className="text-[10px] font-semibold text-slate-600">
      {label}
      <input type="date" name={name} value={value} onChange={onChange} className="mt-1 w-full rounded-lg border border-slate-200 px-2 py-2 text-[11px] outline-none focus:border-blue-500" />
    </label>
  );
}
