import mongoose from 'mongoose';

const clearanceSchema = new mongoose.Schema({
	requestId: {
		type: String,
		default: () => `CLR-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`,
		index: true,
	},
	employee: { type: mongoose.Schema.Types.Mixed, default: '' },
	employeeId: { type: String, default: '' },
	employeeName: { type: String, default: '' },
	department: { type: mongoose.Schema.Types.Mixed, default: '' },
	departmentId: { type: mongoose.Schema.Types.ObjectId, ref: 'Department', default: null, index: true },
	assignedTo: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null, index: true },
	requestSource: { type: String, enum: ['Employee Portal', 'HR Officer'], default: 'Employee Portal', index: true },
	initiatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null, index: true },
	initiatedByName: { type: String, default: '' },
	requestedByRole: { type: String, enum: ['EMPLOYEE', 'HR_OFFICER'], default: 'EMPLOYEE', index: true },
	isHRInitiated: { type: Boolean, default: false, index: true },
	clearanceType: { type: String, default: 'Resignation' },
	reason: { type: String, default: '' },
	requestDate: { type: String, default: '' },
	lastWorkingDate: { type: String, required: true },
	relievingDate: { type: String, default: '' },
	remarks: { type: String, default: '' },
	hrRemarks: { type: String, default: '' },
	manualRoutingEnabled: { type: Boolean, default: false },
	assignedDepartments: { type: [String], default: [] },
	initialHRStatus: { type: String, enum: ['Pending', 'Under Review', 'Approved', 'Returned'], default: 'Pending', index: true },
	initialHRAssessmentCompleted: { type: Boolean, default: false, index: true },
	initialHRRemarks: { type: String, default: '' },
	initialHRReviewedBy: { type: String, default: '' },
	initialHRReviewedById: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
	initialHRReviewedAt: { type: Date, default: null },
	finalHRReviewedBy: { type: String, default: '' },
	finalHRReviewedById: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
	finalHRReviewedByPosition: { type: String, default: '' },
	returnedBy: { type: String, default: '' },
	returnedOffice: { type: String, default: '' },
	returnedAt: { type: Date, default: null },
	returnedReason: { type: String, default: '' },
	returnedRemark: { type: String, default: '' },
	affectedField: { type: String, default: '' },
	requiredOffices: { type: [String], default: ['Department Head', 'Library', 'Finance Office', 'Property / Asset Office', 'ICT Office', 'Transport Office', 'Final HR Clearance'] },
	currentStep: { type: String, default: 'Department Head' },
	workflow: { type: [mongoose.Schema.Types.Mixed], default: [] },
	status: { type: String, enum: ['Pending', 'In Progress', 'Approved', 'Completed', 'Returned', 'Rejected', 'Cancelled'], default: 'Pending' },
	financeStatus: { type: String, enum: ['Pending', 'Under Review', 'In Progress', 'Approved', 'Returned'], default: 'Pending', index: true },
	financeRemarks: { type: String, default: '' },
	financeReviewedBy: { type: String, default: '' },
	financeReviewedById: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
	financeReviewedAt: { type: Date, default: null },
	libraryStatus: { type: String, enum: ['Pending', 'In Progress', 'Completed', 'Returned', 'Rejected'], default: 'Pending' },
	libraryVerificationResult: { type: String, enum: ['Clear', 'Not Clear', ''], default: '' },
	libraryChecklist: { type: [mongoose.Schema.Types.Mixed], default: [] },
	materials: { type: [mongoose.Schema.Types.Mixed], default: [] },
	borrowedItemsStatus: { type: String, enum: ['Clear', 'Not Clear'], default: 'Clear' },
	outstandingFineAmount: { type: Number, min: 0, default: 0 },
	outstandingFineStatus: { type: String, enum: ['Clear', 'Not Clear'], default: 'Clear' },
	libraryComment: { type: String, default: '' },
	libraryReturnReason: { type: String, default: '' },
	libraryReviewedBy: { type: String, default: '' },
	libraryReviewedAt: { type: Date, default: null },
	departmentStatus: { type: String, enum: ['Pending', 'In Progress', 'Approved', 'Returned'], default: 'Pending', index: true },
	departmentReturnReason: { type: String, default: '' },
	departmentReviewedBy: { type: String, default: '' },
	departmentReviewedById: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
	departmentReviewedAt: { type: Date, default: null },
	departmentComment: { type: String, default: '' },
	transportStatus: { type: String, enum: ['', 'Pending', 'Under Review', 'In Progress', 'Approved', 'Returned'], default: '' },
	transportReviewedBy: { type: String, default: '' },
	transportReviewedAt: { type: Date, default: null },
	transportReturnReason: { type: String, default: '' },
	transportOfficerComment: { type: String, default: '' },
	transportReview: { type: mongoose.Schema.Types.Mixed, default: null },
	departmentClearance: { type: mongoose.Schema.Types.Mixed, default: null },
	departmentChecklist: { type: [mongoose.Schema.Types.Mixed], default: [] },
	departmentClearances: { type: [mongoose.Schema.Types.Mixed], default: [] },
	outstandingItems: { type: [String], default: [] },
	checklistCompleted: { type: Boolean, default: false },
	assessmentChecklist: {
		empInfoVerified: { type: Boolean, default: false },
		clearanceRequestVerified: { type: Boolean, default: false },
		documentVerified: { type: Boolean, default: false },
		employmentVerified: { type: Boolean, default: false },
		noDuplicateRequest: { type: Boolean, default: false },
	},
	hrComment: { type: String, default: '' },
	returnReason: { type: String, default: '' },
	certificate: { type: mongoose.Schema.Types.Mixed, default: null },
}, { timestamps: true, strict: false });

const Clearance = mongoose.model('Clearance', clearanceSchema);
export default Clearance;
