import mongoose from 'mongoose';

const employeeSchema = new mongoose.Schema({
	employeeId: { type: String, required: true, trim: true, unique: true },
	firstName: { type: String, trim: true, default: '' },
	middleName: { type: String, trim: true, default: '' },
	lastName: { type: String, trim: true, default: '' },
	fullName: { type: String, required: true, trim: true },
	gender: { type: String, required: true, enum: ['Male', 'Female', 'Other'] },
	nationality: { type: String, required: true, trim: true },
	maritalStatus: { type: String, enum: ['Single', 'Married', 'Divorced', 'Widowed', ''], default: '' },
	dateOfBirth: { type: Date, default: null },
	department: { type: String, required: true, trim: true },
	position: { type: String, required: true, trim: true },
	campus: { type: String, required: true, trim: true },
	category: { type: String, trim: true, default: 'Not specified' },
	employmentType: { type: String, required: true, trim: true },
	hireDate: { type: Date, required: true },
	employmentDate: { type: Date, required: true },
	educationLevel: { type: String, required: true, trim: true },
	roomNumber: { type: String, trim: true, default: '' },
	phone: { type: String, required: true, trim: true },
	email: { type: String, required: true, trim: true, lowercase: true },
	alternativePhone: { type: String, trim: true, default: '' },
	region: { type: String, trim: true, default: '' },
	city: { type: String, trim: true, default: '' },
	subCity: { type: String, trim: true, default: '' },
	woreda: { type: String, trim: true, default: '' },
	kebele: { type: String, trim: true, default: '' },
	nationalId: { type: String, trim: true, default: '' },
	tin: { type: String, trim: true, default: '' },
	address: { type: String, trim: true, default: '' },
	emergencyContact: { type: String, trim: true, default: '' },
	emergencyPhone: { type: String, trim: true, default: '' },
	emergencyContactName: { type: String, trim: true, default: '' },
	emergencyContactPhone: { type: String, trim: true, default: '' },
	emergencyContactRelationship: { type: String, trim: true, default: '' },
	relationship: { type: String, trim: true, default: '' },
	tinNumber: { type: String, trim: true, default: '' },
	bankAccount: { type: String, trim: true, default: '' },
	qualification: { type: String, trim: true, default: '' },
	role: { type: String, default: 'Standard User', trim: true },
	status: { type: String, required: true, enum: ['Active', 'Inactive'], default: 'Active' },
	notes: { type: String, trim: true, default: '' },
	photo: { type: String, default: '' },
	createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
}, { timestamps: true });

const Employee = mongoose.model('Employee', employeeSchema);
export default Employee;